### ISSUE TITLE
Add neo-only client constructors

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dmqproto#17]
There are applications that need completely separate instantiation logic for their neo vs legacy DMQ modes. We already have a way to instantiate a legacy-only client, but no way to instantiate a neo-only client.

**Comment by don-clugston-sociomantic** [comment]
A minimal implementation would be to allow `null` for the legacy config. Currently this doesn't work because it requires the nodes file to exist. I also tried `/dev/null/' as the filename but it seems that it does actually read from the file.

**Comment by gavin-norman-sociomantic** [comment]
Fixed by #44.
