### ISSUE TITLE
D2: Automatically convert tags and push them

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dmqproto#20]
To move forward with D2 we need to provide automatically converted libraries for projects that are built only for D2.

Every time a new tag is pushed, we have to convert it to D2, tag the converted version with a `+d2` build metadata information appended (so tag `v2.3.4` --- conversion D2 ---> `v2.3.4+d2`) and push it back (making sure the new tag is not converted again!).

**Comment by leandro-lucarella-sociomantic** [comment]
This was fixed in the neo branch, how when this will hit the stable channels? I guess we should backport to currently maintained versions. /cc @mathias-lang-sociomantic

**Comment by gavin-norman-sociomantic** [comment]
The neo branch is poised to be merged into v14.x.x, if that helps.

**Comment by mathias-lang-sociomantic** [comment]
That means to v13.2.0+d2 release like the other protos ?

**Comment by leandro-lucarella-sociomantic** [comment]
> The neo branch is poised to be merged into v14.x.x, if that helps.

It's just a simple addition to the `.travis.yml` file, right? It wouldn't be too hard to backport to the other branches I guess.
